version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.10.5
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres/${POSTGRES_DB}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__PARALLELISM: 4
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE: 3
    AIRFLOW__WEBSERVER__WORKERS: 1
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 60
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - project-net
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${PROJECT_DATA}/postgres_data:/var/lib/postgresql/data
    networks:
      - project-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 50s
      retries: 5
      start_period: 5s
    restart: always

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ${PROJECT_DATA}/minio_data:/data
    networks:
      - project-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 256MB

  data_backend:
    image: ghcr.io/${REPO_OWNER}/data_backend:${BACKEND_TAG:-latest}
    networks:
      - project-net

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  psql-init:
    image: postgres:13-alpine
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./postgres/init.sh:/init.sh:ro
    entrypoint: /bin/sh
    command: /init.sh
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AIRFLOW_DB_USER: ${AIRFLOW_DB_USER}
      AIRFLOW_DB_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      FOOTGRAPH_DB: ${FOOTGRAPH_DB}
      FOOTGRAPH_DB_USER: ${FOOTGRAPH_DB_USER}
      FOOTGRAPH_DB_PASSWORD: ${FOOTGRAPH_DB_PASSWORD}
    networks:
      - project-net
    restart: "no"

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        airflow variables set API_FOOTBALL_KEY "${API_FOOTBALL_KEY}"
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_UI_USER}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_UI_PASSWORD}
    user: "0:0"
    volumes:
      - ./airflow:/sources
    depends_on:
      <<: *airflow-common-depends-on
      psql-init:
        condition: service_completed_successfully

volumes:
  postgres_data:
  minio_data:

networks:
  project-net:
