[project]
name = "football_graphs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.13",
    "footgraph",
]

[tool.uv.workspace]
members = ["footgraph"]

[tool.uv.sources]
footgraph = { workspace = true }
