name: Setup Environment
description: Sets up the Python environment.

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.6"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
