name: Docker Build Check

on:
  pull_request:
    paths:
      - "data_backend/**"
      - "Dockerfile"
      - ".github/workflows/build-check.yml"
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build data_backend image (test only)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t test-image:data-backend \
            .