name: Build & Push Backend Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push backend image
        run: |
          TAG=${GITHUB_REF##*/}
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/${{ github.repository_owner }}/data_backend:$TAG \
            -t ghcr.io/${{ github.repository_owner }}/data_backend:latest \
            --push \
            -f Dockerfile \
            .