name: lint-and-test

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Cache dependencies
        id: cache-key
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-deps-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Install the project
        run: uv sync --all-extras --dev

  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        target:
          - path: "scripts/football_api"
          - path: "airflow/dags/"
          - path: "data_backend/"

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-deps-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Run ruff
        run: uv run ruff check ${{ matrix.target.path }}

      - name: Run mypy
        run: uv run mypy --explicit-package-bases ${{ matrix.target.path }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        target:
          - path: "scripts/football_api/tests"
          - path: "data_backend/tests"

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-deps-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Run pytest
        run: uv run pytest ${{ matrix.target.path }}
