name: lint-and-test

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --group airflow --dev

      - name: Minimize uv cache
        run: uv cache prune --ci

  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        target:
          - path: "scripts/football_api"
          - path: "data_backend"
          - path: "airflow/dags"

    steps:
      - uses: actions/checkout@v4

      - name: Restore uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Run ruff
        run: |
          uv tool install ruff
          uv run ruff check ${{ matrix.target.path }}

      - name: Run mypy
        run: |
          uv tool install mypy
          uv run mypy --explicit-package-bases ${{ matrix.target.path }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        target:
          - path: "scripts/football_api"
          - path: "data_backend"
          - path: "airflow"

    steps:
      - uses: actions/checkout@v4

      - name: Restore uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      
      - name: Install dependecies
        run: uv sync --group airflow --dev

      - name: Run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: uv run pytest ${{ matrix.target.path }}/tests
